import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  X,
  Building2,
  ShieldCheck,
  Phone,
  Mail,
  MapPin,
  HelpCircle,
  AlertTriangle,
  Send,
  CheckCircle2,
  Globe,
  FileText,
  Lock,
  Search,
  Sparkles,
  ExternalLink,
  ChevronRight,
  Info
} from 'lucide-react';

export type CompanyPageType = 'about' | 'privacy' | 'contact' | 'faq' | 'disclaimer';

export interface CompanyPagesModalProps {
  isOpen: boolean;
  initialTab?: CompanyPageType;
  onClose: () => void;
}

export const COMPANY_DETAILS = {
  name: 'MarketForge OS',
  parentCompany: 'Scamspike.com',
  address: 'Syuchatar, Nagarjun-9, Kathmandu, Nepal',
  phone: '+9779715312299',
  email: 'solution@scamspike.com',
  website: 'https://scamspike.com',
  supportHours: '24/7 Global Desk | Response SLA < 15 mins'
};

export const CompanyPagesModal: React.FC<CompanyPagesModalProps> = ({
  isOpen,
  initialTab = 'about',
  onClose
}) => {
  const [activeTab, setActiveTab] = useState<CompanyPageType>(initialTab);

  // Sync activeTab if initialTab changes when opening
  React.useEffect(() => {
    if (isOpen && initialTab) {
      setActiveTab(initialTab);
    }
  }, [isOpen, initialTab]);

  // Contact form state
  const [contactName, setContactName] = useState('');
  const [contactEmail, setContactEmail] = useState('');
  const [contactSubject, setContactSubject] = useState('');
  const [contactMessage, setContactMessage] = useState('');
  const [contactSubmitted, setContactSubmitted] = useState(false);

  // FAQ search filter state
  const [faqSearch, setFaqSearch] = useState('');

  const handleContactSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!contactName || !contactEmail || !contactMessage) return;
    setContactSubmitted(true);
    setTimeout(() => {
      setContactSubmitted(false);
      setContactName('');
      setContactEmail('');
      setContactSubject('');
      setContactMessage('');
    }, 4000);
  };

  const FAQS = [
    {
      q: 'What is MarketForge OS and how does it relate to Scamspike.com?',
      a: 'MarketForge OS is an enterprise-grade AI Operating System and unified multi-tenant ERP platform. It is developed and operated under our parent company, Scamspike.com, offering full-stack autonomous AI SDR agents, payroll, supply chain, and CRM infrastructure.'
    },
    {
      q: 'Where is your global headquarters located?',
      a: `Our primary operational engineering hub is located at ${COMPANY_DETAILS.address}. You can reach our executive team directly via email at ${COMPANY_DETAILS.email} or by phone at ${COMPANY_DETAILS.phone}.`
    },
    {
      q: 'How does MarketForge OS ensure 100% data privacy and tenant isolation?',
      a: 'MarketForge OS uses cryptographic tenant key isolation and strict document-level security rules built on Google Cloud Firestore and zero-trust IAM. Your workspace data, financial ledgers, and proprietary AI models are strictly segmented and never mixed across tenant boundaries.'
    },
    {
      q: 'Can I integrate my existing ERP or custom storefront?',
      a: 'Yes! MarketForge OS provides RESTful and GraphQL API bridges, white-label custom domain mapping, and seamless 1-click database synchronization for legacy accounting, inventory, and point-of-sale systems.'
    },
    {
      q: 'How do I contact official technical support or inquire about enterprise pricing?',
      a: `You can reach our dedicated support desk 24/7 by calling ${COMPANY_DETAILS.phone} or emailing ${COMPANY_DETAILS.email}. Our parent entity ${COMPANY_DETAILS.parentCompany} guarantees a response SLA under 15 minutes for enterprise tier tenants.`
    },
    {
      q: 'Is my AI SDR email automation compliant with regional anti-spam regulations?',
      a: 'All Autonomous AI SDR cold outreach sequences generated by MarketForge OS automatically enforce CAN-SPAM, GDPR, and opt-out unsubscribe headers, ensuring high deliverability and compliance across global regions.'
    }
  ];

  const filteredFaqs = FAQS.filter(f => 
    !faqSearch || 
    f.q.toLowerCase().includes(faqSearch.toLowerCase()) || 
    f.a.toLowerCase().includes(faqSearch.toLowerCase())
  );

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-slate-950/80 backdrop-blur-xl overflow-y-auto">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 15 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 15 }}
          className="bg-[#0B0D19] border border-indigo-500/40 rounded-3xl w-full max-w-4xl shadow-2xl overflow-hidden flex flex-col my-auto max-h-[90vh] text-slate-100 relative"
        >
          {/* MODAL HEADER NAV */}
          <div className="p-4 sm:p-6 border-b border-white/10 bg-black/40 flex items-center justify-between shrink-0">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-indigo-500 to-purple-600 p-0.5 shadow-lg flex items-center justify-center shrink-0">
                <div className="w-full h-full bg-[#0B0D19] rounded-[14px] flex items-center justify-center text-cyan-400 font-black">
                  MF
                </div>
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <h3 className="text-lg font-black text-white tracking-tight">{COMPANY_DETAILS.name}</h3>
                  <span className="text-[10px] font-mono text-cyan-400 bg-cyan-500/10 px-2 py-0.5 rounded border border-cyan-500/20">
                    By {COMPANY_DETAILS.parentCompany}
                  </span>
                </div>
                <p className="text-xs text-slate-400 font-mono">
                  Enterprise Governance &amp; Official Company Documentation
                </p>
              </div>
            </div>

            <button
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-white rounded-xl bg-white/5 hover:bg-white/10 transition cursor-pointer"
              title="Close modal"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* PAGE MENU TABS */}
          <div className="bg-[#070814] border-b border-white/10 px-4 py-2 flex items-center gap-2 overflow-x-auto scrollbar-none shrink-0 font-mono text-xs">
            <button
              onClick={() => setActiveTab('about')}
              className={`px-4 py-2 rounded-xl transition flex items-center gap-2 cursor-pointer font-bold whitespace-nowrap ${
                activeTab === 'about'
                  ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md border border-indigo-400/30'
                  : 'text-slate-400 hover:text-white hover:bg-white/5'
              }`}
            >
              <Building2 className="w-4 h-4" />
              About Us
            </button>

            <button
              onClick={() => setActiveTab('privacy')}
              className={`px-4 py-2 rounded-xl transition flex items-center gap-2 cursor-pointer font-bold whitespace-nowrap ${
                activeTab === 'privacy'
                  ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md border border-indigo-400/30'
                  : 'text-slate-400 hover:text-white hover:bg-white/5'
              }`}
            >
              <ShieldCheck className="w-4 h-4" />
              Privacy Policy
            </button>

            <button
              onClick={() => setActiveTab('contact')}
              className={`px-4 py-2 rounded-xl transition flex items-center gap-2 cursor-pointer font-bold whitespace-nowrap ${
                activeTab === 'contact'
                  ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md border border-indigo-400/30'
                  : 'text-slate-400 hover:text-white hover:bg-white/5'
              }`}
            >
              <Phone className="w-4 h-4" />
              Contact Us
            </button>

            <button
              onClick={() => setActiveTab('faq')}
              className={`px-4 py-2 rounded-xl transition flex items-center gap-2 cursor-pointer font-bold whitespace-nowrap ${
                activeTab === 'faq'
                  ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md border border-indigo-400/30'
                  : 'text-slate-400 hover:text-white hover:bg-white/5'
              }`}
            >
              <HelpCircle className="w-4 h-4" />
              FAQ
            </button>

            <button
              onClick={() => setActiveTab('disclaimer')}
              className={`px-4 py-2 rounded-xl transition flex items-center gap-2 cursor-pointer font-bold whitespace-nowrap ${
                activeTab === 'disclaimer'
                  ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md border border-indigo-400/30'
                  : 'text-slate-400 hover:text-white hover:bg-white/5'
              }`}
            >
              <AlertTriangle className="w-4 h-4" />
              Disclaimer
            </button>
          </div>

          {/* PAGE CONTENT CONTAINER */}
          <div className="p-6 overflow-y-auto space-y-6 flex-1 text-sm font-sans leading-relaxed">

            {/* TAB 1: ABOUT US */}
            {activeTab === 'about' && (
              <div className="space-y-6 animate-in fade-in duration-200">
                <div className="p-5 bg-gradient-to-r from-indigo-950/60 via-purple-950/40 to-cyan-950/40 border border-indigo-500/30 rounded-2xl space-y-2">
                  <div className="text-[10px] font-mono text-cyan-300 font-bold uppercase tracking-wider flex items-center gap-2">
                    <Sparkles className="w-3.5 h-3.5 text-cyan-400" /> Executive Overview
                  </div>
                  <h2 className="text-2xl font-black text-white">About MarketForge OS</h2>
                  <p className="text-slate-300 text-xs sm:text-sm">
                    MarketForge OS is an all-in-one AI Operating System designed to replace fragmented SaaS tools with an autonomous, high-throughput business workspace.
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="p-4 bg-slate-900/80 border border-white/10 rounded-2xl space-y-2">
                    <h4 className="text-sm font-bold text-white flex items-center gap-2 font-mono">
                      <Building2 className="w-4 h-4 text-indigo-400" /> Parent Entity &amp; Mission
                    </h4>
                    <p className="text-xs text-slate-300">
                      Operated under our parent organization <span className="text-cyan-300 font-bold font-mono">{COMPANY_DETAILS.parentCompany}</span>, MarketForge OS delivers unified sales pipelines, autonomous AI SDR prospectors, POS inventory management, and global HR &amp; payroll infrastructure.
                    </p>
                  </div>

                  <div className="p-4 bg-slate-900/80 border border-white/10 rounded-2xl space-y-2">
                    <h4 className="text-sm font-bold text-white flex items-center gap-2 font-mono">
                      <MapPin className="w-4 h-4 text-rose-400" /> Global Headquarters Location
                    </h4>
                    <p className="text-xs text-slate-300 font-mono">
                      {COMPANY_DETAILS.address}
                    </p>
                    <div className="text-[11px] text-slate-400 pt-1">
                      Direct Hub Line: <span className="text-emerald-400 font-bold">{COMPANY_DETAILS.phone}</span>
                    </div>
                  </div>
                </div>

                <div className="p-5 bg-black/40 border border-white/10 rounded-2xl space-y-3">
                  <h3 className="text-base font-bold text-white">Core Pillars of Excellence</h3>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
                    <div className="p-3 bg-white/5 border border-white/5 rounded-xl space-y-1">
                      <div className="font-bold text-indigo-300 font-mono">100% Tenant Isolation</div>
                      <p className="text-slate-400 text-[11px]">Strict multi-tenant security guarantees zero cross-contamination of company databases.</p>
                    </div>
                    <div className="p-3 bg-white/5 border border-white/5 rounded-xl space-y-1">
                      <div className="font-bold text-cyan-300 font-mono">Autonomous AI Core</div>
                      <p className="text-slate-400 text-[11px]">Self-healing CRM enrichment, cold email sequence generation, and live support routing.</p>
                    </div>
                    <div className="p-3 bg-white/5 border border-white/5 rounded-xl space-y-1">
                      <div className="font-bold text-emerald-300 font-mono">24/7 Global SLA</div>
                      <p className="text-slate-400 text-[11px]">Backed by executive support engineers directly reachable at {COMPANY_DETAILS.email}.</p>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* TAB 2: PRIVACY POLICY */}
            {activeTab === 'privacy' && (
              <div className="space-y-6 animate-in fade-in duration-200">
                <div className="border-b border-white/10 pb-3">
                  <div className="text-[10px] font-mono text-emerald-400 font-bold uppercase tracking-wider mb-1">
                    Effective Date: August 2026 • Version 2.4
                  </div>
                  <h2 className="text-2xl font-black text-white">Privacy Policy</h2>
                  <p className="text-slate-400 text-xs mt-1">
                    Official Privacy and Data Protection Framework for MarketForge OS and parent entity {COMPANY_DETAILS.parentCompany}.
                  </p>
                </div>

                <div className="space-y-4 text-xs text-slate-300">
                  <section className="space-y-1.5 p-4 bg-slate-900/60 border border-white/10 rounded-2xl">
                    <h3 className="text-sm font-bold text-white font-mono flex items-center gap-2">
                      <Lock className="w-4 h-4 text-indigo-400" /> 1. Information Collection &amp; Scope
                    </h3>
                    <p>
                      MarketForge OS collects business account identifiers, workspace logs, tenant transaction ledgers, and contact emails purely to facilitate operating system services. We do NOT sell, rent, or monetize your company or customer data to third-party ad networks.
                    </p>
                  </section>

                  <section className="space-y-1.5 p-4 bg-slate-900/60 border border-white/10 rounded-2xl">
                    <h3 className="text-sm font-bold text-white font-mono flex items-center gap-2">
                      <ShieldCheck className="w-4 h-4 text-emerald-400" /> 2. Multi-Tenant Data Isolation
                    </h3>
                    <p>
                      Each tenant workspace is isolated with cryptographic security barriers. Data submitted to MarketForge OS is processed within dedicated Firestore database security collections, governed by parent entity <span className="text-white font-mono">{COMPANY_DETAILS.parentCompany}</span>.
                    </p>
                  </section>

                  <section className="space-y-1.5 p-4 bg-slate-900/60 border border-white/10 rounded-2xl">
                    <h3 className="text-sm font-bold text-white font-mono flex items-center gap-2">
                      <Mail className="w-4 h-4 text-cyan-400" /> 3. Data Protection Officer &amp; Inquiries
                    </h3>
                    <p>
                      For privacy requests, GDPR deletion, or security disclosures, please contact our Data Protection Team at <span className="text-cyan-300 font-mono">{COMPANY_DETAILS.email}</span> or write to our registered office:
                    </p>
                    <div className="p-2.5 bg-black/40 border border-white/10 rounded-xl text-[11px] font-mono text-slate-300 mt-2">
                      <div><strong className="text-white">Parent Entity:</strong> {COMPANY_DETAILS.parentCompany}</div>
                      <div><strong className="text-white">Address:</strong> {COMPANY_DETAILS.address}</div>
                      <div><strong className="text-white">Phone:</strong> {COMPANY_DETAILS.phone}</div>
                    </div>
                  </section>
                </div>
              </div>
            )}

            {/* TAB 3: CONTACT US */}
            {activeTab === 'contact' && (
              <div className="space-y-6 animate-in fade-in duration-200">
                <div className="border-b border-white/10 pb-3">
                  <h2 className="text-2xl font-black text-white">Contact Executive Team</h2>
                  <p className="text-slate-400 text-xs mt-1">
                    Get in touch with MarketForge OS and our parent company {COMPANY_DETAILS.parentCompany}.
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div className="p-4 bg-indigo-950/40 border border-indigo-500/30 rounded-2xl space-y-2">
                    <div className="w-8 h-8 rounded-xl bg-indigo-500/20 text-indigo-300 flex items-center justify-center">
                      <MapPin className="w-4 h-4" />
                    </div>
                    <div className="text-xs font-mono font-bold text-indigo-300 uppercase">Registered Address</div>
                    <div className="text-xs text-slate-200 font-mono leading-relaxed">
                      {COMPANY_DETAILS.address}
                    </div>
                    <div className="text-[10px] text-slate-400 pt-1 font-mono">
                      Parent: {COMPANY_DETAILS.parentCompany}
                    </div>
                  </div>

                  <div className="p-4 bg-cyan-950/40 border border-cyan-500/30 rounded-2xl space-y-2">
                    <div className="w-8 h-8 rounded-xl bg-cyan-500/20 text-cyan-300 flex items-center justify-center">
                      <Phone className="w-4 h-4" />
                    </div>
                    <div className="text-xs font-mono font-bold text-cyan-300 uppercase">Direct Phone Line</div>
                    <div className="text-sm text-white font-mono font-bold">
                      {COMPANY_DETAILS.phone}
                    </div>
                    <div className="text-[10px] text-slate-400 pt-1 font-mono">
                      Available 24/7 for Enterprise
                    </div>
                  </div>

                  <div className="p-4 bg-purple-950/40 border border-purple-500/30 rounded-2xl space-y-2">
                    <div className="w-8 h-8 rounded-xl bg-purple-500/20 text-purple-300 flex items-center justify-center">
                      <Mail className="w-4 h-4" />
                    </div>
                    <div className="text-xs font-mono font-bold text-purple-300 uppercase">Official Support Email</div>
                    <div className="text-xs text-white font-mono font-bold truncate">
                      {COMPANY_DETAILS.email}
                    </div>
                    <div className="text-[10px] text-slate-400 pt-1 font-mono">
                      Response SLA &lt; 15 mins
                    </div>
                  </div>
                </div>

                {/* INTERACTIVE INQUIRY FORM */}
                <form onSubmit={handleContactSubmit} className="p-5 bg-black/50 border border-white/10 rounded-2xl space-y-4 font-sans">
                  <h3 className="text-sm font-mono font-bold text-white uppercase tracking-wider flex items-center gap-2">
                    <Send className="w-4 h-4 text-cyan-400" /> Direct Executive Inquiry Form
                  </h3>

                  {contactSubmitted && (
                    <div className="p-3.5 bg-emerald-950/80 border border-emerald-500/50 rounded-xl text-emerald-200 text-xs flex items-center gap-2.5">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                      <span>Inquiry transmitted successfully to <strong className="text-white">{COMPANY_DETAILS.email}</strong>! Our executive desk will follow up shortly.</span>
                    </div>
                  )}

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                    <div>
                      <label className="text-[10px] font-mono text-slate-400 block mb-1">Your Full Name *</label>
                      <input
                        type="text"
                        value={contactName}
                        onChange={e => setContactName(e.target.value)}
                        placeholder="e.g. Alexander Vance"
                        className="w-full bg-slate-900 border border-white/15 rounded-xl px-3 py-2 text-white font-mono focus:outline-none focus:border-cyan-500"
                        required
                      />
                    </div>

                    <div>
                      <label className="text-[10px] font-mono text-slate-400 block mb-1">Business Email Address *</label>
                      <input
                        type="email"
                        value={contactEmail}
                        onChange={e => setContactEmail(e.target.value)}
                        placeholder="e.g. alex@enterprise.com"
                        className="w-full bg-slate-900 border border-white/15 rounded-xl px-3 py-2 text-white font-mono focus:outline-none focus:border-cyan-500"
                        required
                      />
                    </div>
                  </div>

                  <div>
                    <label className="text-[10px] font-mono text-slate-400 block mb-1">Subject</label>
                    <input
                      type="text"
                      value={contactSubject}
                      onChange={e => setContactSubject(e.target.value)}
                      placeholder="e.g. Enterprise Migration Inquiry"
                      className="w-full bg-slate-900 border border-white/15 rounded-xl px-3 py-2 text-white font-mono focus:outline-none focus:border-cyan-500"
                    />
                  </div>

                  <div>
                    <label className="text-[10px] font-mono text-slate-400 block mb-1">Message / Requirements *</label>
                    <textarea
                      rows={3}
                      value={contactMessage}
                      onChange={e => setContactMessage(e.target.value)}
                      placeholder="Specify your workspace or customization inquiry..."
                      className="w-full bg-slate-900 border border-white/15 rounded-xl px-3 py-2 text-white font-sans text-xs focus:outline-none focus:border-cyan-500"
                      required
                    />
                  </div>

                  <div className="flex items-center justify-between pt-1">
                    <span className="text-[10px] font-mono text-slate-500">
                      Transmitted directly to {COMPANY_DETAILS.email}
                    </span>
                    <button
                      type="submit"
                      className="px-6 py-2.5 bg-gradient-to-r from-cyan-600 to-indigo-600 hover:from-cyan-500 hover:to-indigo-500 text-white font-mono text-xs font-bold rounded-xl shadow-lg cursor-pointer transition flex items-center gap-2"
                    >
                      <Send className="w-3.5 h-3.5" /> Transmit Message
                    </button>
                  </div>
                </form>
              </div>
            )}

            {/* TAB 4: FAQ */}
            {activeTab === 'faq' && (
              <div className="space-y-6 animate-in fade-in duration-200">
                <div className="border-b border-white/10 pb-3 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                  <div>
                    <h2 className="text-2xl font-black text-white">Frequently Asked Questions</h2>
                    <p className="text-slate-400 text-xs mt-1">
                      Everything you need to know about MarketForge OS and parent entity {COMPANY_DETAILS.parentCompany}.
                    </p>
                  </div>

                  {/* FAQ Search bar */}
                  <div className="relative w-full sm:w-64">
                    <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
                    <input
                      type="text"
                      value={faqSearch}
                      onChange={e => setFaqSearch(e.target.value)}
                      placeholder="Search FAQ..."
                      className="w-full pl-9 pr-3 py-1.5 bg-slate-900 border border-white/15 rounded-xl text-xs font-mono text-white focus:outline-none focus:border-indigo-500"
                    />
                  </div>
                </div>

                <div className="space-y-3">
                  {filteredFaqs.length > 0 ? (
                    filteredFaqs.map((faq, idx) => (
                      <div key={idx} className="p-4 bg-slate-900/80 border border-white/10 rounded-2xl space-y-2">
                        <h4 className="text-sm font-bold text-white flex items-start gap-2">
                          <HelpCircle className="w-4 h-4 text-indigo-400 shrink-0 mt-0.5" />
                          <span>{faq.q}</span>
                        </h4>
                        <p className="text-xs text-slate-300 leading-relaxed pl-6">
                          {faq.a}
                        </p>
                      </div>
                    ))
                  ) : (
                    <div className="text-center py-8 text-slate-400 text-xs font-mono">
                      No matching questions found for "{faqSearch}". Reach our executive desk at {COMPANY_DETAILS.email}.
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* TAB 5: DISCLAIMER */}
            {activeTab === 'disclaimer' && (
              <div className="space-y-6 animate-in fade-in duration-200">
                <div className="border-b border-white/10 pb-3">
                  <div className="text-[10px] font-mono text-amber-400 font-bold uppercase tracking-wider mb-1">
                    Legal &amp; Operational Notice
                  </div>
                  <h2 className="text-2xl font-black text-white">Platform Disclaimer</h2>
                  <p className="text-slate-400 text-xs mt-1">
                    Official terms governing platform usage, AI SDR automation, and services rendered by parent entity {COMPANY_DETAILS.parentCompany}.
                  </p>
                </div>

                <div className="space-y-4 text-xs text-slate-300">
                  <div className="p-4 bg-amber-950/40 border border-amber-500/30 rounded-2xl space-y-2">
                    <h3 className="text-sm font-bold text-amber-300 font-mono flex items-center gap-2">
                      <AlertTriangle className="w-4 h-4 text-amber-400" /> 1. Autonomous AI Output Disclaimer
                    </h3>
                    <p>
                      MarketForge OS utilizes advanced generative AI models for prospect outreach, automated customer replies, and financial reporting projections. While models are optimized for accuracy, tenant administrators are responsible for reviewing automated communications sent on behalf of their organization.
                    </p>
                  </div>

                  <div className="p-4 bg-slate-900/60 border border-white/10 rounded-2xl space-y-2">
                    <h3 className="text-sm font-bold text-white font-mono flex items-center gap-2">
                      <FileText className="w-4 h-4 text-indigo-400" /> 2. Financial &amp; Tax Ledger Compliance
                    </h3>
                    <p>
                      Financial double-entry ledgers and automated cashflow forecasts generated within MarketForge OS are built for operational management. Tenant organizations should consult certified local tax authorities regarding regional tax filings and compliance.
                    </p>
                  </div>

                  <div className="p-4 bg-slate-900/60 border border-white/10 rounded-2xl space-y-2">
                    <h3 className="text-sm font-bold text-white font-mono flex items-center gap-2">
                      <Globe className="w-4 h-4 text-cyan-400" /> 3. Corporate Entity &amp; Jurisdiction
                    </h3>
                    <p>
                      MarketForge OS is owned and operated by <span className="text-white font-mono font-bold">{COMPANY_DETAILS.parentCompany}</span>, registered at <span className="text-cyan-300 font-mono">{COMPANY_DETAILS.address}</span>. All service level agreements and legal notices fall under corporate jurisdiction. Direct contact: <span className="text-emerald-400 font-mono">{COMPANY_DETAILS.phone}</span> or <span className="text-emerald-400 font-mono">{COMPANY_DETAILS.email}</span>.
                    </p>
                  </div>
                </div>
              </div>
            )}

          </div>

          {/* FOOTER BAR */}
          <div className="p-4 border-t border-white/10 bg-black/60 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs font-mono text-slate-400 shrink-0">
            <div className="flex items-center gap-2 text-[11px]">
              <span className="text-slate-300 font-bold">{COMPANY_DETAILS.name}</span>
              <span>•</span>
              <span className="text-cyan-300">{COMPANY_DETAILS.parentCompany}</span>
              <span>•</span>
              <span>{COMPANY_DETAILS.phone}</span>
            </div>

            <div className="flex items-center gap-2 text-[11px]">
              <span className="text-slate-400">{COMPANY_DETAILS.email}</span>
              <button
                onClick={onClose}
                className="px-4 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-lg transition cursor-pointer ml-2"
              >
                Close Window
              </button>
            </div>
          </div>

        </motion.div>
      </div>
    </AnimatePresence>
  );
};

export default CompanyPagesModal;
